// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResourceMetadata.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ResourceMetadata_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ResourceMetadata_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ResourceMetadata_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ResourceMetadata_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ResourceMetadata_2eproto;
namespace aapt {
namespace pb {
class CollapsedNamesMap;
struct CollapsedNamesMapDefaultTypeInternal;
extern CollapsedNamesMapDefaultTypeInternal _CollapsedNamesMap_default_instance_;
class CollapsedNamesMap_ResourceNameMapping;
struct CollapsedNamesMap_ResourceNameMappingDefaultTypeInternal;
extern CollapsedNamesMap_ResourceNameMappingDefaultTypeInternal _CollapsedNamesMap_ResourceNameMapping_default_instance_;
class ResourceMappings;
struct ResourceMappingsDefaultTypeInternal;
extern ResourceMappingsDefaultTypeInternal _ResourceMappings_default_instance_;
class ShortenedPathsMap;
struct ShortenedPathsMapDefaultTypeInternal;
extern ShortenedPathsMapDefaultTypeInternal _ShortenedPathsMap_default_instance_;
class ShortenedPathsMap_ResourcePathMapping;
struct ShortenedPathsMap_ResourcePathMappingDefaultTypeInternal;
extern ShortenedPathsMap_ResourcePathMappingDefaultTypeInternal _ShortenedPathsMap_ResourcePathMapping_default_instance_;
}  // namespace pb
}  // namespace aapt
PROTOBUF_NAMESPACE_OPEN
template<> ::aapt::pb::CollapsedNamesMap* Arena::CreateMaybeMessage<::aapt::pb::CollapsedNamesMap>(Arena*);
template<> ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* Arena::CreateMaybeMessage<::aapt::pb::CollapsedNamesMap_ResourceNameMapping>(Arena*);
template<> ::aapt::pb::ResourceMappings* Arena::CreateMaybeMessage<::aapt::pb::ResourceMappings>(Arena*);
template<> ::aapt::pb::ShortenedPathsMap* Arena::CreateMaybeMessage<::aapt::pb::ShortenedPathsMap>(Arena*);
template<> ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* Arena::CreateMaybeMessage<::aapt::pb::ShortenedPathsMap_ResourcePathMapping>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace aapt {
namespace pb {

// ===================================================================

class ResourceMappings final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aapt.pb.ResourceMappings) */ {
 public:
  inline ResourceMappings() : ResourceMappings(nullptr) {}
  ~ResourceMappings() override;
  explicit PROTOBUF_CONSTEXPR ResourceMappings(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ResourceMappings(const ResourceMappings& from);
  ResourceMappings(ResourceMappings&& from) noexcept
    : ResourceMappings() {
    *this = ::std::move(from);
  }

  inline ResourceMappings& operator=(const ResourceMappings& from) {
    CopyFrom(from);
    return *this;
  }
  inline ResourceMappings& operator=(ResourceMappings&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ResourceMappings& default_instance() {
    return *internal_default_instance();
  }
  static inline const ResourceMappings* internal_default_instance() {
    return reinterpret_cast<const ResourceMappings*>(
               &_ResourceMappings_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ResourceMappings& a, ResourceMappings& b) {
    a.Swap(&b);
  }
  inline void Swap(ResourceMappings* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ResourceMappings* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ResourceMappings* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ResourceMappings>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ResourceMappings& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ResourceMappings& from) {
    ResourceMappings::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ResourceMappings* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aapt.pb.ResourceMappings";
  }
  protected:
  explicit ResourceMappings(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShortenedPathsFieldNumber = 1,
    kCollapsedNamesFieldNumber = 2,
  };
  // .aapt.pb.ShortenedPathsMap shortened_paths = 1;
  bool has_shortened_paths() const;
  private:
  bool _internal_has_shortened_paths() const;
  public:
  void clear_shortened_paths();
  const ::aapt::pb::ShortenedPathsMap& shortened_paths() const;
  PROTOBUF_NODISCARD ::aapt::pb::ShortenedPathsMap* release_shortened_paths();
  ::aapt::pb::ShortenedPathsMap* mutable_shortened_paths();
  void set_allocated_shortened_paths(::aapt::pb::ShortenedPathsMap* shortened_paths);
  private:
  const ::aapt::pb::ShortenedPathsMap& _internal_shortened_paths() const;
  ::aapt::pb::ShortenedPathsMap* _internal_mutable_shortened_paths();
  public:
  void unsafe_arena_set_allocated_shortened_paths(
      ::aapt::pb::ShortenedPathsMap* shortened_paths);
  ::aapt::pb::ShortenedPathsMap* unsafe_arena_release_shortened_paths();

  // .aapt.pb.CollapsedNamesMap collapsed_names = 2;
  bool has_collapsed_names() const;
  private:
  bool _internal_has_collapsed_names() const;
  public:
  void clear_collapsed_names();
  const ::aapt::pb::CollapsedNamesMap& collapsed_names() const;
  PROTOBUF_NODISCARD ::aapt::pb::CollapsedNamesMap* release_collapsed_names();
  ::aapt::pb::CollapsedNamesMap* mutable_collapsed_names();
  void set_allocated_collapsed_names(::aapt::pb::CollapsedNamesMap* collapsed_names);
  private:
  const ::aapt::pb::CollapsedNamesMap& _internal_collapsed_names() const;
  ::aapt::pb::CollapsedNamesMap* _internal_mutable_collapsed_names();
  public:
  void unsafe_arena_set_allocated_collapsed_names(
      ::aapt::pb::CollapsedNamesMap* collapsed_names);
  ::aapt::pb::CollapsedNamesMap* unsafe_arena_release_collapsed_names();

  // @@protoc_insertion_point(class_scope:aapt.pb.ResourceMappings)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::aapt::pb::ShortenedPathsMap* shortened_paths_;
    ::aapt::pb::CollapsedNamesMap* collapsed_names_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ResourceMetadata_2eproto;
};
// -------------------------------------------------------------------

class ShortenedPathsMap_ResourcePathMapping final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aapt.pb.ShortenedPathsMap.ResourcePathMapping) */ {
 public:
  inline ShortenedPathsMap_ResourcePathMapping() : ShortenedPathsMap_ResourcePathMapping(nullptr) {}
  ~ShortenedPathsMap_ResourcePathMapping() override;
  explicit PROTOBUF_CONSTEXPR ShortenedPathsMap_ResourcePathMapping(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShortenedPathsMap_ResourcePathMapping(const ShortenedPathsMap_ResourcePathMapping& from);
  ShortenedPathsMap_ResourcePathMapping(ShortenedPathsMap_ResourcePathMapping&& from) noexcept
    : ShortenedPathsMap_ResourcePathMapping() {
    *this = ::std::move(from);
  }

  inline ShortenedPathsMap_ResourcePathMapping& operator=(const ShortenedPathsMap_ResourcePathMapping& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShortenedPathsMap_ResourcePathMapping& operator=(ShortenedPathsMap_ResourcePathMapping&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShortenedPathsMap_ResourcePathMapping& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShortenedPathsMap_ResourcePathMapping* internal_default_instance() {
    return reinterpret_cast<const ShortenedPathsMap_ResourcePathMapping*>(
               &_ShortenedPathsMap_ResourcePathMapping_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ShortenedPathsMap_ResourcePathMapping& a, ShortenedPathsMap_ResourcePathMapping& b) {
    a.Swap(&b);
  }
  inline void Swap(ShortenedPathsMap_ResourcePathMapping* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShortenedPathsMap_ResourcePathMapping* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShortenedPathsMap_ResourcePathMapping* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShortenedPathsMap_ResourcePathMapping>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShortenedPathsMap_ResourcePathMapping& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShortenedPathsMap_ResourcePathMapping& from) {
    ShortenedPathsMap_ResourcePathMapping::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShortenedPathsMap_ResourcePathMapping* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aapt.pb.ShortenedPathsMap.ResourcePathMapping";
  }
  protected:
  explicit ShortenedPathsMap_ResourcePathMapping(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kShortenedPathFieldNumber = 1,
    kOriginalPathFieldNumber = 2,
  };
  // string shortened_path = 1;
  void clear_shortened_path();
  const std::string& shortened_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_shortened_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_shortened_path();
  PROTOBUF_NODISCARD std::string* release_shortened_path();
  void set_allocated_shortened_path(std::string* shortened_path);
  private:
  const std::string& _internal_shortened_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_shortened_path(const std::string& value);
  std::string* _internal_mutable_shortened_path();
  public:

  // string original_path = 2;
  void clear_original_path();
  const std::string& original_path() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_original_path(ArgT0&& arg0, ArgT... args);
  std::string* mutable_original_path();
  PROTOBUF_NODISCARD std::string* release_original_path();
  void set_allocated_original_path(std::string* original_path);
  private:
  const std::string& _internal_original_path() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_original_path(const std::string& value);
  std::string* _internal_mutable_original_path();
  public:

  // @@protoc_insertion_point(class_scope:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr shortened_path_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr original_path_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ResourceMetadata_2eproto;
};
// -------------------------------------------------------------------

class ShortenedPathsMap final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aapt.pb.ShortenedPathsMap) */ {
 public:
  inline ShortenedPathsMap() : ShortenedPathsMap(nullptr) {}
  ~ShortenedPathsMap() override;
  explicit PROTOBUF_CONSTEXPR ShortenedPathsMap(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ShortenedPathsMap(const ShortenedPathsMap& from);
  ShortenedPathsMap(ShortenedPathsMap&& from) noexcept
    : ShortenedPathsMap() {
    *this = ::std::move(from);
  }

  inline ShortenedPathsMap& operator=(const ShortenedPathsMap& from) {
    CopyFrom(from);
    return *this;
  }
  inline ShortenedPathsMap& operator=(ShortenedPathsMap&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ShortenedPathsMap& default_instance() {
    return *internal_default_instance();
  }
  static inline const ShortenedPathsMap* internal_default_instance() {
    return reinterpret_cast<const ShortenedPathsMap*>(
               &_ShortenedPathsMap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ShortenedPathsMap& a, ShortenedPathsMap& b) {
    a.Swap(&b);
  }
  inline void Swap(ShortenedPathsMap* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ShortenedPathsMap* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ShortenedPathsMap* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ShortenedPathsMap>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ShortenedPathsMap& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ShortenedPathsMap& from) {
    ShortenedPathsMap::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ShortenedPathsMap* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aapt.pb.ShortenedPathsMap";
  }
  protected:
  explicit ShortenedPathsMap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef ShortenedPathsMap_ResourcePathMapping ResourcePathMapping;

  // accessors -------------------------------------------------------

  enum : int {
    kResourcePathsFieldNumber = 1,
  };
  // repeated .aapt.pb.ShortenedPathsMap.ResourcePathMapping resource_paths = 1;
  int resource_paths_size() const;
  private:
  int _internal_resource_paths_size() const;
  public:
  void clear_resource_paths();
  ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* mutable_resource_paths(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::ShortenedPathsMap_ResourcePathMapping >*
      mutable_resource_paths();
  private:
  const ::aapt::pb::ShortenedPathsMap_ResourcePathMapping& _internal_resource_paths(int index) const;
  ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* _internal_add_resource_paths();
  public:
  const ::aapt::pb::ShortenedPathsMap_ResourcePathMapping& resource_paths(int index) const;
  ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* add_resource_paths();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::ShortenedPathsMap_ResourcePathMapping >&
      resource_paths() const;

  // @@protoc_insertion_point(class_scope:aapt.pb.ShortenedPathsMap)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::ShortenedPathsMap_ResourcePathMapping > resource_paths_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ResourceMetadata_2eproto;
};
// -------------------------------------------------------------------

class CollapsedNamesMap_ResourceNameMapping final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aapt.pb.CollapsedNamesMap.ResourceNameMapping) */ {
 public:
  inline CollapsedNamesMap_ResourceNameMapping() : CollapsedNamesMap_ResourceNameMapping(nullptr) {}
  ~CollapsedNamesMap_ResourceNameMapping() override;
  explicit PROTOBUF_CONSTEXPR CollapsedNamesMap_ResourceNameMapping(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CollapsedNamesMap_ResourceNameMapping(const CollapsedNamesMap_ResourceNameMapping& from);
  CollapsedNamesMap_ResourceNameMapping(CollapsedNamesMap_ResourceNameMapping&& from) noexcept
    : CollapsedNamesMap_ResourceNameMapping() {
    *this = ::std::move(from);
  }

  inline CollapsedNamesMap_ResourceNameMapping& operator=(const CollapsedNamesMap_ResourceNameMapping& from) {
    CopyFrom(from);
    return *this;
  }
  inline CollapsedNamesMap_ResourceNameMapping& operator=(CollapsedNamesMap_ResourceNameMapping&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CollapsedNamesMap_ResourceNameMapping& default_instance() {
    return *internal_default_instance();
  }
  static inline const CollapsedNamesMap_ResourceNameMapping* internal_default_instance() {
    return reinterpret_cast<const CollapsedNamesMap_ResourceNameMapping*>(
               &_CollapsedNamesMap_ResourceNameMapping_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(CollapsedNamesMap_ResourceNameMapping& a, CollapsedNamesMap_ResourceNameMapping& b) {
    a.Swap(&b);
  }
  inline void Swap(CollapsedNamesMap_ResourceNameMapping* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CollapsedNamesMap_ResourceNameMapping* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CollapsedNamesMap_ResourceNameMapping* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CollapsedNamesMap_ResourceNameMapping>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CollapsedNamesMap_ResourceNameMapping& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CollapsedNamesMap_ResourceNameMapping& from) {
    CollapsedNamesMap_ResourceNameMapping::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CollapsedNamesMap_ResourceNameMapping* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aapt.pb.CollapsedNamesMap.ResourceNameMapping";
  }
  protected:
  explicit CollapsedNamesMap_ResourceNameMapping(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kIdFieldNumber = 1,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // uint32 id = 1;
  void clear_id();
  uint32_t id() const;
  void set_id(uint32_t value);
  private:
  uint32_t _internal_id() const;
  void _internal_set_id(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    uint32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ResourceMetadata_2eproto;
};
// -------------------------------------------------------------------

class CollapsedNamesMap final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:aapt.pb.CollapsedNamesMap) */ {
 public:
  inline CollapsedNamesMap() : CollapsedNamesMap(nullptr) {}
  ~CollapsedNamesMap() override;
  explicit PROTOBUF_CONSTEXPR CollapsedNamesMap(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  CollapsedNamesMap(const CollapsedNamesMap& from);
  CollapsedNamesMap(CollapsedNamesMap&& from) noexcept
    : CollapsedNamesMap() {
    *this = ::std::move(from);
  }

  inline CollapsedNamesMap& operator=(const CollapsedNamesMap& from) {
    CopyFrom(from);
    return *this;
  }
  inline CollapsedNamesMap& operator=(CollapsedNamesMap&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CollapsedNamesMap& default_instance() {
    return *internal_default_instance();
  }
  static inline const CollapsedNamesMap* internal_default_instance() {
    return reinterpret_cast<const CollapsedNamesMap*>(
               &_CollapsedNamesMap_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(CollapsedNamesMap& a, CollapsedNamesMap& b) {
    a.Swap(&b);
  }
  inline void Swap(CollapsedNamesMap* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CollapsedNamesMap* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CollapsedNamesMap* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<CollapsedNamesMap>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const CollapsedNamesMap& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const CollapsedNamesMap& from) {
    CollapsedNamesMap::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(CollapsedNamesMap* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "aapt.pb.CollapsedNamesMap";
  }
  protected:
  explicit CollapsedNamesMap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  typedef CollapsedNamesMap_ResourceNameMapping ResourceNameMapping;

  // accessors -------------------------------------------------------

  enum : int {
    kResourceNamesFieldNumber = 1,
  };
  // repeated .aapt.pb.CollapsedNamesMap.ResourceNameMapping resource_names = 1;
  int resource_names_size() const;
  private:
  int _internal_resource_names_size() const;
  public:
  void clear_resource_names();
  ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* mutable_resource_names(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::CollapsedNamesMap_ResourceNameMapping >*
      mutable_resource_names();
  private:
  const ::aapt::pb::CollapsedNamesMap_ResourceNameMapping& _internal_resource_names(int index) const;
  ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* _internal_add_resource_names();
  public:
  const ::aapt::pb::CollapsedNamesMap_ResourceNameMapping& resource_names(int index) const;
  ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* add_resource_names();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::CollapsedNamesMap_ResourceNameMapping >&
      resource_names() const;

  // @@protoc_insertion_point(class_scope:aapt.pb.CollapsedNamesMap)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::CollapsedNamesMap_ResourceNameMapping > resource_names_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ResourceMetadata_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ResourceMappings

// .aapt.pb.ShortenedPathsMap shortened_paths = 1;
inline bool ResourceMappings::_internal_has_shortened_paths() const {
  return this != internal_default_instance() && _impl_.shortened_paths_ != nullptr;
}
inline bool ResourceMappings::has_shortened_paths() const {
  return _internal_has_shortened_paths();
}
inline void ResourceMappings::clear_shortened_paths() {
  if (GetArenaForAllocation() == nullptr && _impl_.shortened_paths_ != nullptr) {
    delete _impl_.shortened_paths_;
  }
  _impl_.shortened_paths_ = nullptr;
}
inline const ::aapt::pb::ShortenedPathsMap& ResourceMappings::_internal_shortened_paths() const {
  const ::aapt::pb::ShortenedPathsMap* p = _impl_.shortened_paths_;
  return p != nullptr ? *p : reinterpret_cast<const ::aapt::pb::ShortenedPathsMap&>(
      ::aapt::pb::_ShortenedPathsMap_default_instance_);
}
inline const ::aapt::pb::ShortenedPathsMap& ResourceMappings::shortened_paths() const {
  // @@protoc_insertion_point(field_get:aapt.pb.ResourceMappings.shortened_paths)
  return _internal_shortened_paths();
}
inline void ResourceMappings::unsafe_arena_set_allocated_shortened_paths(
    ::aapt::pb::ShortenedPathsMap* shortened_paths) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.shortened_paths_);
  }
  _impl_.shortened_paths_ = shortened_paths;
  if (shortened_paths) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aapt.pb.ResourceMappings.shortened_paths)
}
inline ::aapt::pb::ShortenedPathsMap* ResourceMappings::release_shortened_paths() {
  
  ::aapt::pb::ShortenedPathsMap* temp = _impl_.shortened_paths_;
  _impl_.shortened_paths_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aapt::pb::ShortenedPathsMap* ResourceMappings::unsafe_arena_release_shortened_paths() {
  // @@protoc_insertion_point(field_release:aapt.pb.ResourceMappings.shortened_paths)
  
  ::aapt::pb::ShortenedPathsMap* temp = _impl_.shortened_paths_;
  _impl_.shortened_paths_ = nullptr;
  return temp;
}
inline ::aapt::pb::ShortenedPathsMap* ResourceMappings::_internal_mutable_shortened_paths() {
  
  if (_impl_.shortened_paths_ == nullptr) {
    auto* p = CreateMaybeMessage<::aapt::pb::ShortenedPathsMap>(GetArenaForAllocation());
    _impl_.shortened_paths_ = p;
  }
  return _impl_.shortened_paths_;
}
inline ::aapt::pb::ShortenedPathsMap* ResourceMappings::mutable_shortened_paths() {
  ::aapt::pb::ShortenedPathsMap* _msg = _internal_mutable_shortened_paths();
  // @@protoc_insertion_point(field_mutable:aapt.pb.ResourceMappings.shortened_paths)
  return _msg;
}
inline void ResourceMappings::set_allocated_shortened_paths(::aapt::pb::ShortenedPathsMap* shortened_paths) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.shortened_paths_;
  }
  if (shortened_paths) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(shortened_paths);
    if (message_arena != submessage_arena) {
      shortened_paths = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, shortened_paths, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.shortened_paths_ = shortened_paths;
  // @@protoc_insertion_point(field_set_allocated:aapt.pb.ResourceMappings.shortened_paths)
}

// .aapt.pb.CollapsedNamesMap collapsed_names = 2;
inline bool ResourceMappings::_internal_has_collapsed_names() const {
  return this != internal_default_instance() && _impl_.collapsed_names_ != nullptr;
}
inline bool ResourceMappings::has_collapsed_names() const {
  return _internal_has_collapsed_names();
}
inline void ResourceMappings::clear_collapsed_names() {
  if (GetArenaForAllocation() == nullptr && _impl_.collapsed_names_ != nullptr) {
    delete _impl_.collapsed_names_;
  }
  _impl_.collapsed_names_ = nullptr;
}
inline const ::aapt::pb::CollapsedNamesMap& ResourceMappings::_internal_collapsed_names() const {
  const ::aapt::pb::CollapsedNamesMap* p = _impl_.collapsed_names_;
  return p != nullptr ? *p : reinterpret_cast<const ::aapt::pb::CollapsedNamesMap&>(
      ::aapt::pb::_CollapsedNamesMap_default_instance_);
}
inline const ::aapt::pb::CollapsedNamesMap& ResourceMappings::collapsed_names() const {
  // @@protoc_insertion_point(field_get:aapt.pb.ResourceMappings.collapsed_names)
  return _internal_collapsed_names();
}
inline void ResourceMappings::unsafe_arena_set_allocated_collapsed_names(
    ::aapt::pb::CollapsedNamesMap* collapsed_names) {
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(_impl_.collapsed_names_);
  }
  _impl_.collapsed_names_ = collapsed_names;
  if (collapsed_names) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:aapt.pb.ResourceMappings.collapsed_names)
}
inline ::aapt::pb::CollapsedNamesMap* ResourceMappings::release_collapsed_names() {
  
  ::aapt::pb::CollapsedNamesMap* temp = _impl_.collapsed_names_;
  _impl_.collapsed_names_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old =  reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(temp);
  temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  if (GetArenaForAllocation() == nullptr) { delete old; }
#else  // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return temp;
}
inline ::aapt::pb::CollapsedNamesMap* ResourceMappings::unsafe_arena_release_collapsed_names() {
  // @@protoc_insertion_point(field_release:aapt.pb.ResourceMappings.collapsed_names)
  
  ::aapt::pb::CollapsedNamesMap* temp = _impl_.collapsed_names_;
  _impl_.collapsed_names_ = nullptr;
  return temp;
}
inline ::aapt::pb::CollapsedNamesMap* ResourceMappings::_internal_mutable_collapsed_names() {
  
  if (_impl_.collapsed_names_ == nullptr) {
    auto* p = CreateMaybeMessage<::aapt::pb::CollapsedNamesMap>(GetArenaForAllocation());
    _impl_.collapsed_names_ = p;
  }
  return _impl_.collapsed_names_;
}
inline ::aapt::pb::CollapsedNamesMap* ResourceMappings::mutable_collapsed_names() {
  ::aapt::pb::CollapsedNamesMap* _msg = _internal_mutable_collapsed_names();
  // @@protoc_insertion_point(field_mutable:aapt.pb.ResourceMappings.collapsed_names)
  return _msg;
}
inline void ResourceMappings::set_allocated_collapsed_names(::aapt::pb::CollapsedNamesMap* collapsed_names) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArenaForAllocation();
  if (message_arena == nullptr) {
    delete _impl_.collapsed_names_;
  }
  if (collapsed_names) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
        ::PROTOBUF_NAMESPACE_ID::Arena::InternalGetOwningArena(collapsed_names);
    if (message_arena != submessage_arena) {
      collapsed_names = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, collapsed_names, submessage_arena);
    }
    
  } else {
    
  }
  _impl_.collapsed_names_ = collapsed_names;
  // @@protoc_insertion_point(field_set_allocated:aapt.pb.ResourceMappings.collapsed_names)
}

// -------------------------------------------------------------------

// ShortenedPathsMap_ResourcePathMapping

// string shortened_path = 1;
inline void ShortenedPathsMap_ResourcePathMapping::clear_shortened_path() {
  _impl_.shortened_path_.ClearToEmpty();
}
inline const std::string& ShortenedPathsMap_ResourcePathMapping::shortened_path() const {
  // @@protoc_insertion_point(field_get:aapt.pb.ShortenedPathsMap.ResourcePathMapping.shortened_path)
  return _internal_shortened_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShortenedPathsMap_ResourcePathMapping::set_shortened_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.shortened_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aapt.pb.ShortenedPathsMap.ResourcePathMapping.shortened_path)
}
inline std::string* ShortenedPathsMap_ResourcePathMapping::mutable_shortened_path() {
  std::string* _s = _internal_mutable_shortened_path();
  // @@protoc_insertion_point(field_mutable:aapt.pb.ShortenedPathsMap.ResourcePathMapping.shortened_path)
  return _s;
}
inline const std::string& ShortenedPathsMap_ResourcePathMapping::_internal_shortened_path() const {
  return _impl_.shortened_path_.Get();
}
inline void ShortenedPathsMap_ResourcePathMapping::_internal_set_shortened_path(const std::string& value) {
  
  _impl_.shortened_path_.Set(value, GetArenaForAllocation());
}
inline std::string* ShortenedPathsMap_ResourcePathMapping::_internal_mutable_shortened_path() {
  
  return _impl_.shortened_path_.Mutable(GetArenaForAllocation());
}
inline std::string* ShortenedPathsMap_ResourcePathMapping::release_shortened_path() {
  // @@protoc_insertion_point(field_release:aapt.pb.ShortenedPathsMap.ResourcePathMapping.shortened_path)
  return _impl_.shortened_path_.Release();
}
inline void ShortenedPathsMap_ResourcePathMapping::set_allocated_shortened_path(std::string* shortened_path) {
  if (shortened_path != nullptr) {
    
  } else {
    
  }
  _impl_.shortened_path_.SetAllocated(shortened_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.shortened_path_.IsDefault()) {
    _impl_.shortened_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aapt.pb.ShortenedPathsMap.ResourcePathMapping.shortened_path)
}

// string original_path = 2;
inline void ShortenedPathsMap_ResourcePathMapping::clear_original_path() {
  _impl_.original_path_.ClearToEmpty();
}
inline const std::string& ShortenedPathsMap_ResourcePathMapping::original_path() const {
  // @@protoc_insertion_point(field_get:aapt.pb.ShortenedPathsMap.ResourcePathMapping.original_path)
  return _internal_original_path();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ShortenedPathsMap_ResourcePathMapping::set_original_path(ArgT0&& arg0, ArgT... args) {
 
 _impl_.original_path_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aapt.pb.ShortenedPathsMap.ResourcePathMapping.original_path)
}
inline std::string* ShortenedPathsMap_ResourcePathMapping::mutable_original_path() {
  std::string* _s = _internal_mutable_original_path();
  // @@protoc_insertion_point(field_mutable:aapt.pb.ShortenedPathsMap.ResourcePathMapping.original_path)
  return _s;
}
inline const std::string& ShortenedPathsMap_ResourcePathMapping::_internal_original_path() const {
  return _impl_.original_path_.Get();
}
inline void ShortenedPathsMap_ResourcePathMapping::_internal_set_original_path(const std::string& value) {
  
  _impl_.original_path_.Set(value, GetArenaForAllocation());
}
inline std::string* ShortenedPathsMap_ResourcePathMapping::_internal_mutable_original_path() {
  
  return _impl_.original_path_.Mutable(GetArenaForAllocation());
}
inline std::string* ShortenedPathsMap_ResourcePathMapping::release_original_path() {
  // @@protoc_insertion_point(field_release:aapt.pb.ShortenedPathsMap.ResourcePathMapping.original_path)
  return _impl_.original_path_.Release();
}
inline void ShortenedPathsMap_ResourcePathMapping::set_allocated_original_path(std::string* original_path) {
  if (original_path != nullptr) {
    
  } else {
    
  }
  _impl_.original_path_.SetAllocated(original_path, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.original_path_.IsDefault()) {
    _impl_.original_path_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aapt.pb.ShortenedPathsMap.ResourcePathMapping.original_path)
}

// -------------------------------------------------------------------

// ShortenedPathsMap

// repeated .aapt.pb.ShortenedPathsMap.ResourcePathMapping resource_paths = 1;
inline int ShortenedPathsMap::_internal_resource_paths_size() const {
  return _impl_.resource_paths_.size();
}
inline int ShortenedPathsMap::resource_paths_size() const {
  return _internal_resource_paths_size();
}
inline void ShortenedPathsMap::clear_resource_paths() {
  _impl_.resource_paths_.Clear();
}
inline ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* ShortenedPathsMap::mutable_resource_paths(int index) {
  // @@protoc_insertion_point(field_mutable:aapt.pb.ShortenedPathsMap.resource_paths)
  return _impl_.resource_paths_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::ShortenedPathsMap_ResourcePathMapping >*
ShortenedPathsMap::mutable_resource_paths() {
  // @@protoc_insertion_point(field_mutable_list:aapt.pb.ShortenedPathsMap.resource_paths)
  return &_impl_.resource_paths_;
}
inline const ::aapt::pb::ShortenedPathsMap_ResourcePathMapping& ShortenedPathsMap::_internal_resource_paths(int index) const {
  return _impl_.resource_paths_.Get(index);
}
inline const ::aapt::pb::ShortenedPathsMap_ResourcePathMapping& ShortenedPathsMap::resource_paths(int index) const {
  // @@protoc_insertion_point(field_get:aapt.pb.ShortenedPathsMap.resource_paths)
  return _internal_resource_paths(index);
}
inline ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* ShortenedPathsMap::_internal_add_resource_paths() {
  return _impl_.resource_paths_.Add();
}
inline ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* ShortenedPathsMap::add_resource_paths() {
  ::aapt::pb::ShortenedPathsMap_ResourcePathMapping* _add = _internal_add_resource_paths();
  // @@protoc_insertion_point(field_add:aapt.pb.ShortenedPathsMap.resource_paths)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::ShortenedPathsMap_ResourcePathMapping >&
ShortenedPathsMap::resource_paths() const {
  // @@protoc_insertion_point(field_list:aapt.pb.ShortenedPathsMap.resource_paths)
  return _impl_.resource_paths_;
}

// -------------------------------------------------------------------

// CollapsedNamesMap_ResourceNameMapping

// uint32 id = 1;
inline void CollapsedNamesMap_ResourceNameMapping::clear_id() {
  _impl_.id_ = 0u;
}
inline uint32_t CollapsedNamesMap_ResourceNameMapping::_internal_id() const {
  return _impl_.id_;
}
inline uint32_t CollapsedNamesMap_ResourceNameMapping::id() const {
  // @@protoc_insertion_point(field_get:aapt.pb.CollapsedNamesMap.ResourceNameMapping.id)
  return _internal_id();
}
inline void CollapsedNamesMap_ResourceNameMapping::_internal_set_id(uint32_t value) {
  
  _impl_.id_ = value;
}
inline void CollapsedNamesMap_ResourceNameMapping::set_id(uint32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:aapt.pb.CollapsedNamesMap.ResourceNameMapping.id)
}

// string name = 2;
inline void CollapsedNamesMap_ResourceNameMapping::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& CollapsedNamesMap_ResourceNameMapping::name() const {
  // @@protoc_insertion_point(field_get:aapt.pb.CollapsedNamesMap.ResourceNameMapping.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void CollapsedNamesMap_ResourceNameMapping::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:aapt.pb.CollapsedNamesMap.ResourceNameMapping.name)
}
inline std::string* CollapsedNamesMap_ResourceNameMapping::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:aapt.pb.CollapsedNamesMap.ResourceNameMapping.name)
  return _s;
}
inline const std::string& CollapsedNamesMap_ResourceNameMapping::_internal_name() const {
  return _impl_.name_.Get();
}
inline void CollapsedNamesMap_ResourceNameMapping::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* CollapsedNamesMap_ResourceNameMapping::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* CollapsedNamesMap_ResourceNameMapping::release_name() {
  // @@protoc_insertion_point(field_release:aapt.pb.CollapsedNamesMap.ResourceNameMapping.name)
  return _impl_.name_.Release();
}
inline void CollapsedNamesMap_ResourceNameMapping::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:aapt.pb.CollapsedNamesMap.ResourceNameMapping.name)
}

// -------------------------------------------------------------------

// CollapsedNamesMap

// repeated .aapt.pb.CollapsedNamesMap.ResourceNameMapping resource_names = 1;
inline int CollapsedNamesMap::_internal_resource_names_size() const {
  return _impl_.resource_names_.size();
}
inline int CollapsedNamesMap::resource_names_size() const {
  return _internal_resource_names_size();
}
inline void CollapsedNamesMap::clear_resource_names() {
  _impl_.resource_names_.Clear();
}
inline ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* CollapsedNamesMap::mutable_resource_names(int index) {
  // @@protoc_insertion_point(field_mutable:aapt.pb.CollapsedNamesMap.resource_names)
  return _impl_.resource_names_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::CollapsedNamesMap_ResourceNameMapping >*
CollapsedNamesMap::mutable_resource_names() {
  // @@protoc_insertion_point(field_mutable_list:aapt.pb.CollapsedNamesMap.resource_names)
  return &_impl_.resource_names_;
}
inline const ::aapt::pb::CollapsedNamesMap_ResourceNameMapping& CollapsedNamesMap::_internal_resource_names(int index) const {
  return _impl_.resource_names_.Get(index);
}
inline const ::aapt::pb::CollapsedNamesMap_ResourceNameMapping& CollapsedNamesMap::resource_names(int index) const {
  // @@protoc_insertion_point(field_get:aapt.pb.CollapsedNamesMap.resource_names)
  return _internal_resource_names(index);
}
inline ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* CollapsedNamesMap::_internal_add_resource_names() {
  return _impl_.resource_names_.Add();
}
inline ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* CollapsedNamesMap::add_resource_names() {
  ::aapt::pb::CollapsedNamesMap_ResourceNameMapping* _add = _internal_add_resource_names();
  // @@protoc_insertion_point(field_add:aapt.pb.CollapsedNamesMap.resource_names)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::aapt::pb::CollapsedNamesMap_ResourceNameMapping >&
CollapsedNamesMap::resource_names() const {
  // @@protoc_insertion_point(field_list:aapt.pb.CollapsedNamesMap.resource_names)
  return _impl_.resource_names_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb
}  // namespace aapt

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ResourceMetadata_2eproto
