// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ResourceMetadata.proto

#include "ResourceMetadata.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace aapt {
namespace pb {
PROTOBUF_CONSTEXPR ResourceMappings::ResourceMappings(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.shortened_paths_)*/nullptr
  , /*decltype(_impl_.collapsed_names_)*/nullptr
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ResourceMappingsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ResourceMappingsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ResourceMappingsDefaultTypeInternal() {}
  union {
    ResourceMappings _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ResourceMappingsDefaultTypeInternal _ResourceMappings_default_instance_;
PROTOBUF_CONSTEXPR ShortenedPathsMap_ResourcePathMapping::ShortenedPathsMap_ResourcePathMapping(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.shortened_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.original_path_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ShortenedPathsMap_ResourcePathMappingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShortenedPathsMap_ResourcePathMappingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShortenedPathsMap_ResourcePathMappingDefaultTypeInternal() {}
  union {
    ShortenedPathsMap_ResourcePathMapping _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShortenedPathsMap_ResourcePathMappingDefaultTypeInternal _ShortenedPathsMap_ResourcePathMapping_default_instance_;
PROTOBUF_CONSTEXPR ShortenedPathsMap::ShortenedPathsMap(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.resource_paths_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ShortenedPathsMapDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ShortenedPathsMapDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ShortenedPathsMapDefaultTypeInternal() {}
  union {
    ShortenedPathsMap _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ShortenedPathsMapDefaultTypeInternal _ShortenedPathsMap_default_instance_;
PROTOBUF_CONSTEXPR CollapsedNamesMap_ResourceNameMapping::CollapsedNamesMap_ResourceNameMapping(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.id_)*/0u
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CollapsedNamesMap_ResourceNameMappingDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CollapsedNamesMap_ResourceNameMappingDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CollapsedNamesMap_ResourceNameMappingDefaultTypeInternal() {}
  union {
    CollapsedNamesMap_ResourceNameMapping _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CollapsedNamesMap_ResourceNameMappingDefaultTypeInternal _CollapsedNamesMap_ResourceNameMapping_default_instance_;
PROTOBUF_CONSTEXPR CollapsedNamesMap::CollapsedNamesMap(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.resource_names_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct CollapsedNamesMapDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CollapsedNamesMapDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CollapsedNamesMapDefaultTypeInternal() {}
  union {
    CollapsedNamesMap _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CollapsedNamesMapDefaultTypeInternal _CollapsedNamesMap_default_instance_;
}  // namespace pb
}  // namespace aapt
static ::_pb::Metadata file_level_metadata_ResourceMetadata_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ResourceMetadata_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ResourceMetadata_2eproto = nullptr;

const uint32_t TableStruct_ResourceMetadata_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ResourceMappings, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ResourceMappings, _impl_.shortened_paths_),
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ResourceMappings, _impl_.collapsed_names_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ShortenedPathsMap_ResourcePathMapping, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ShortenedPathsMap_ResourcePathMapping, _impl_.shortened_path_),
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ShortenedPathsMap_ResourcePathMapping, _impl_.original_path_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ShortenedPathsMap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::ShortenedPathsMap, _impl_.resource_paths_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::CollapsedNamesMap_ResourceNameMapping, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::CollapsedNamesMap_ResourceNameMapping, _impl_.id_),
  PROTOBUF_FIELD_OFFSET(::aapt::pb::CollapsedNamesMap_ResourceNameMapping, _impl_.name_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::CollapsedNamesMap, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::aapt::pb::CollapsedNamesMap, _impl_.resource_names_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, -1, sizeof(::aapt::pb::ResourceMappings)},
  { 8, -1, -1, sizeof(::aapt::pb::ShortenedPathsMap_ResourcePathMapping)},
  { 16, -1, -1, sizeof(::aapt::pb::ShortenedPathsMap)},
  { 23, -1, -1, sizeof(::aapt::pb::CollapsedNamesMap_ResourceNameMapping)},
  { 31, -1, -1, sizeof(::aapt::pb::CollapsedNamesMap)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::aapt::pb::_ResourceMappings_default_instance_._instance,
  &::aapt::pb::_ShortenedPathsMap_ResourcePathMapping_default_instance_._instance,
  &::aapt::pb::_ShortenedPathsMap_default_instance_._instance,
  &::aapt::pb::_CollapsedNamesMap_ResourceNameMapping_default_instance_._instance,
  &::aapt::pb::_CollapsedNamesMap_default_instance_._instance,
};

const char descriptor_table_protodef_ResourceMetadata_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\026ResourceMetadata.proto\022\007aapt.pb\"|\n\020Res"
  "ourceMappings\0223\n\017shortened_paths\030\001 \001(\0132\032"
  ".aapt.pb.ShortenedPathsMap\0223\n\017collapsed_"
  "names\030\002 \001(\0132\032.aapt.pb.CollapsedNamesMap\""
  "\241\001\n\021ShortenedPathsMap\022F\n\016resource_paths\030"
  "\001 \003(\0132..aapt.pb.ShortenedPathsMap.Resour"
  "cePathMapping\032D\n\023ResourcePathMapping\022\026\n\016"
  "shortened_path\030\001 \001(\t\022\025\n\roriginal_path\030\002 "
  "\001(\t\"\214\001\n\021CollapsedNamesMap\022F\n\016resource_na"
  "mes\030\001 \003(\0132..aapt.pb.CollapsedNamesMap.Re"
  "sourceNameMapping\032/\n\023ResourceNameMapping"
  "\022\n\n\002id\030\001 \001(\r\022\014\n\004name\030\002 \001(\tB\024\n\020com.androi"
  "d.aaptP\001b\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ResourceMetadata_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ResourceMetadata_2eproto = {
    false, false, 496, descriptor_table_protodef_ResourceMetadata_2eproto,
    "ResourceMetadata.proto",
    &descriptor_table_ResourceMetadata_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_ResourceMetadata_2eproto::offsets,
    file_level_metadata_ResourceMetadata_2eproto, file_level_enum_descriptors_ResourceMetadata_2eproto,
    file_level_service_descriptors_ResourceMetadata_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ResourceMetadata_2eproto_getter() {
  return &descriptor_table_ResourceMetadata_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ResourceMetadata_2eproto(&descriptor_table_ResourceMetadata_2eproto);
namespace aapt {
namespace pb {

// ===================================================================

class ResourceMappings::_Internal {
 public:
  static const ::aapt::pb::ShortenedPathsMap& shortened_paths(const ResourceMappings* msg);
  static const ::aapt::pb::CollapsedNamesMap& collapsed_names(const ResourceMappings* msg);
};

const ::aapt::pb::ShortenedPathsMap&
ResourceMappings::_Internal::shortened_paths(const ResourceMappings* msg) {
  return *msg->_impl_.shortened_paths_;
}
const ::aapt::pb::CollapsedNamesMap&
ResourceMappings::_Internal::collapsed_names(const ResourceMappings* msg) {
  return *msg->_impl_.collapsed_names_;
}
ResourceMappings::ResourceMappings(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:aapt.pb.ResourceMappings)
}
ResourceMappings::ResourceMappings(const ResourceMappings& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ResourceMappings* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.shortened_paths_){nullptr}
    , decltype(_impl_.collapsed_names_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  if (from._internal_has_shortened_paths()) {
    _this->_impl_.shortened_paths_ = new ::aapt::pb::ShortenedPathsMap(*from._impl_.shortened_paths_);
  }
  if (from._internal_has_collapsed_names()) {
    _this->_impl_.collapsed_names_ = new ::aapt::pb::CollapsedNamesMap(*from._impl_.collapsed_names_);
  }
  // @@protoc_insertion_point(copy_constructor:aapt.pb.ResourceMappings)
}

inline void ResourceMappings::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.shortened_paths_){nullptr}
    , decltype(_impl_.collapsed_names_){nullptr}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ResourceMappings::~ResourceMappings() {
  // @@protoc_insertion_point(destructor:aapt.pb.ResourceMappings)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ResourceMappings::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  if (this != internal_default_instance()) delete _impl_.shortened_paths_;
  if (this != internal_default_instance()) delete _impl_.collapsed_names_;
}

void ResourceMappings::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ResourceMappings::Clear() {
// @@protoc_insertion_point(message_clear_start:aapt.pb.ResourceMappings)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaForAllocation() == nullptr && _impl_.shortened_paths_ != nullptr) {
    delete _impl_.shortened_paths_;
  }
  _impl_.shortened_paths_ = nullptr;
  if (GetArenaForAllocation() == nullptr && _impl_.collapsed_names_ != nullptr) {
    delete _impl_.collapsed_names_;
  }
  _impl_.collapsed_names_ = nullptr;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ResourceMappings::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // .aapt.pb.ShortenedPathsMap shortened_paths = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr = ctx->ParseMessage(_internal_mutable_shortened_paths(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // .aapt.pb.CollapsedNamesMap collapsed_names = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          ptr = ctx->ParseMessage(_internal_mutable_collapsed_names(), ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ResourceMappings::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aapt.pb.ResourceMappings)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // .aapt.pb.ShortenedPathsMap shortened_paths = 1;
  if (this->_internal_has_shortened_paths()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(1, _Internal::shortened_paths(this),
        _Internal::shortened_paths(this).GetCachedSize(), target, stream);
  }

  // .aapt.pb.CollapsedNamesMap collapsed_names = 2;
  if (this->_internal_has_collapsed_names()) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, _Internal::collapsed_names(this),
        _Internal::collapsed_names(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aapt.pb.ResourceMappings)
  return target;
}

size_t ResourceMappings::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aapt.pb.ResourceMappings)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // .aapt.pb.ShortenedPathsMap shortened_paths = 1;
  if (this->_internal_has_shortened_paths()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.shortened_paths_);
  }

  // .aapt.pb.CollapsedNamesMap collapsed_names = 2;
  if (this->_internal_has_collapsed_names()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(
        *_impl_.collapsed_names_);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ResourceMappings::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ResourceMappings::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ResourceMappings::GetClassData() const { return &_class_data_; }


void ResourceMappings::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ResourceMappings*>(&to_msg);
  auto& from = static_cast<const ResourceMappings&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aapt.pb.ResourceMappings)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_has_shortened_paths()) {
    _this->_internal_mutable_shortened_paths()->::aapt::pb::ShortenedPathsMap::MergeFrom(
        from._internal_shortened_paths());
  }
  if (from._internal_has_collapsed_names()) {
    _this->_internal_mutable_collapsed_names()->::aapt::pb::CollapsedNamesMap::MergeFrom(
        from._internal_collapsed_names());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ResourceMappings::CopyFrom(const ResourceMappings& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aapt.pb.ResourceMappings)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ResourceMappings::IsInitialized() const {
  return true;
}

void ResourceMappings::InternalSwap(ResourceMappings* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ResourceMappings, _impl_.collapsed_names_)
      + sizeof(ResourceMappings::_impl_.collapsed_names_)
      - PROTOBUF_FIELD_OFFSET(ResourceMappings, _impl_.shortened_paths_)>(
          reinterpret_cast<char*>(&_impl_.shortened_paths_),
          reinterpret_cast<char*>(&other->_impl_.shortened_paths_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ResourceMappings::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ResourceMetadata_2eproto_getter, &descriptor_table_ResourceMetadata_2eproto_once,
      file_level_metadata_ResourceMetadata_2eproto[0]);
}

// ===================================================================

class ShortenedPathsMap_ResourcePathMapping::_Internal {
 public:
};

ShortenedPathsMap_ResourcePathMapping::ShortenedPathsMap_ResourcePathMapping(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
}
ShortenedPathsMap_ResourcePathMapping::ShortenedPathsMap_ResourcePathMapping(const ShortenedPathsMap_ResourcePathMapping& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ShortenedPathsMap_ResourcePathMapping* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.shortened_path_){}
    , decltype(_impl_.original_path_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.shortened_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.shortened_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_shortened_path().empty()) {
    _this->_impl_.shortened_path_.Set(from._internal_shortened_path(), 
      _this->GetArenaForAllocation());
  }
  _impl_.original_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.original_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_original_path().empty()) {
    _this->_impl_.original_path_.Set(from._internal_original_path(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
}

inline void ShortenedPathsMap_ResourcePathMapping::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.shortened_path_){}
    , decltype(_impl_.original_path_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.shortened_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.shortened_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.original_path_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.original_path_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ShortenedPathsMap_ResourcePathMapping::~ShortenedPathsMap_ResourcePathMapping() {
  // @@protoc_insertion_point(destructor:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ShortenedPathsMap_ResourcePathMapping::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.shortened_path_.Destroy();
  _impl_.original_path_.Destroy();
}

void ShortenedPathsMap_ResourcePathMapping::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ShortenedPathsMap_ResourcePathMapping::Clear() {
// @@protoc_insertion_point(message_clear_start:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.shortened_path_.ClearToEmpty();
  _impl_.original_path_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShortenedPathsMap_ResourcePathMapping::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string shortened_path = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_shortened_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "aapt.pb.ShortenedPathsMap.ResourcePathMapping.shortened_path"));
        } else
          goto handle_unusual;
        continue;
      // string original_path = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_original_path();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "aapt.pb.ShortenedPathsMap.ResourcePathMapping.original_path"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ShortenedPathsMap_ResourcePathMapping::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string shortened_path = 1;
  if (!this->_internal_shortened_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_shortened_path().data(), static_cast<int>(this->_internal_shortened_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "aapt.pb.ShortenedPathsMap.ResourcePathMapping.shortened_path");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_shortened_path(), target);
  }

  // string original_path = 2;
  if (!this->_internal_original_path().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_original_path().data(), static_cast<int>(this->_internal_original_path().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "aapt.pb.ShortenedPathsMap.ResourcePathMapping.original_path");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_original_path(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
  return target;
}

size_t ShortenedPathsMap_ResourcePathMapping::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string shortened_path = 1;
  if (!this->_internal_shortened_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_shortened_path());
  }

  // string original_path = 2;
  if (!this->_internal_original_path().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_original_path());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ShortenedPathsMap_ResourcePathMapping::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ShortenedPathsMap_ResourcePathMapping::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ShortenedPathsMap_ResourcePathMapping::GetClassData() const { return &_class_data_; }


void ShortenedPathsMap_ResourcePathMapping::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ShortenedPathsMap_ResourcePathMapping*>(&to_msg);
  auto& from = static_cast<const ShortenedPathsMap_ResourcePathMapping&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_shortened_path().empty()) {
    _this->_internal_set_shortened_path(from._internal_shortened_path());
  }
  if (!from._internal_original_path().empty()) {
    _this->_internal_set_original_path(from._internal_original_path());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ShortenedPathsMap_ResourcePathMapping::CopyFrom(const ShortenedPathsMap_ResourcePathMapping& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aapt.pb.ShortenedPathsMap.ResourcePathMapping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShortenedPathsMap_ResourcePathMapping::IsInitialized() const {
  return true;
}

void ShortenedPathsMap_ResourcePathMapping::InternalSwap(ShortenedPathsMap_ResourcePathMapping* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.shortened_path_, lhs_arena,
      &other->_impl_.shortened_path_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.original_path_, lhs_arena,
      &other->_impl_.original_path_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata ShortenedPathsMap_ResourcePathMapping::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ResourceMetadata_2eproto_getter, &descriptor_table_ResourceMetadata_2eproto_once,
      file_level_metadata_ResourceMetadata_2eproto[1]);
}

// ===================================================================

class ShortenedPathsMap::_Internal {
 public:
};

ShortenedPathsMap::ShortenedPathsMap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:aapt.pb.ShortenedPathsMap)
}
ShortenedPathsMap::ShortenedPathsMap(const ShortenedPathsMap& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ShortenedPathsMap* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_paths_){from._impl_.resource_paths_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:aapt.pb.ShortenedPathsMap)
}

inline void ShortenedPathsMap::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_paths_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ShortenedPathsMap::~ShortenedPathsMap() {
  // @@protoc_insertion_point(destructor:aapt.pb.ShortenedPathsMap)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ShortenedPathsMap::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.resource_paths_.~RepeatedPtrField();
}

void ShortenedPathsMap::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ShortenedPathsMap::Clear() {
// @@protoc_insertion_point(message_clear_start:aapt.pb.ShortenedPathsMap)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resource_paths_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ShortenedPathsMap::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .aapt.pb.ShortenedPathsMap.ResourcePathMapping resource_paths = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_resource_paths(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ShortenedPathsMap::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aapt.pb.ShortenedPathsMap)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .aapt.pb.ShortenedPathsMap.ResourcePathMapping resource_paths = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_resource_paths_size()); i < n; i++) {
    const auto& repfield = this->_internal_resource_paths(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aapt.pb.ShortenedPathsMap)
  return target;
}

size_t ShortenedPathsMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aapt.pb.ShortenedPathsMap)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .aapt.pb.ShortenedPathsMap.ResourcePathMapping resource_paths = 1;
  total_size += 1UL * this->_internal_resource_paths_size();
  for (const auto& msg : this->_impl_.resource_paths_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ShortenedPathsMap::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ShortenedPathsMap::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ShortenedPathsMap::GetClassData() const { return &_class_data_; }


void ShortenedPathsMap::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ShortenedPathsMap*>(&to_msg);
  auto& from = static_cast<const ShortenedPathsMap&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aapt.pb.ShortenedPathsMap)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.resource_paths_.MergeFrom(from._impl_.resource_paths_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ShortenedPathsMap::CopyFrom(const ShortenedPathsMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aapt.pb.ShortenedPathsMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShortenedPathsMap::IsInitialized() const {
  return true;
}

void ShortenedPathsMap::InternalSwap(ShortenedPathsMap* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.resource_paths_.InternalSwap(&other->_impl_.resource_paths_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ShortenedPathsMap::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ResourceMetadata_2eproto_getter, &descriptor_table_ResourceMetadata_2eproto_once,
      file_level_metadata_ResourceMetadata_2eproto[2]);
}

// ===================================================================

class CollapsedNamesMap_ResourceNameMapping::_Internal {
 public:
};

CollapsedNamesMap_ResourceNameMapping::CollapsedNamesMap_ResourceNameMapping(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
}
CollapsedNamesMap_ResourceNameMapping::CollapsedNamesMap_ResourceNameMapping(const CollapsedNamesMap_ResourceNameMapping& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CollapsedNamesMap_ResourceNameMapping* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.id_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _this->_impl_.id_ = from._impl_.id_;
  // @@protoc_insertion_point(copy_constructor:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
}

inline void CollapsedNamesMap_ResourceNameMapping::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.id_){0u}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

CollapsedNamesMap_ResourceNameMapping::~CollapsedNamesMap_ResourceNameMapping() {
  // @@protoc_insertion_point(destructor:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CollapsedNamesMap_ResourceNameMapping::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
}

void CollapsedNamesMap_ResourceNameMapping::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CollapsedNamesMap_ResourceNameMapping::Clear() {
// @@protoc_insertion_point(message_clear_start:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CollapsedNamesMap_ResourceNameMapping::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // uint32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "aapt.pb.CollapsedNamesMap.ResourceNameMapping.name"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CollapsedNamesMap_ResourceNameMapping::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(1, this->_internal_id(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "aapt.pb.CollapsedNamesMap.ResourceNameMapping.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
  return target;
}

size_t CollapsedNamesMap_ResourceNameMapping::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // uint32 id = 1;
  if (this->_internal_id() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(this->_internal_id());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CollapsedNamesMap_ResourceNameMapping::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CollapsedNamesMap_ResourceNameMapping::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CollapsedNamesMap_ResourceNameMapping::GetClassData() const { return &_class_data_; }


void CollapsedNamesMap_ResourceNameMapping::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CollapsedNamesMap_ResourceNameMapping*>(&to_msg);
  auto& from = static_cast<const CollapsedNamesMap_ResourceNameMapping&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_id() != 0) {
    _this->_internal_set_id(from._internal_id());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CollapsedNamesMap_ResourceNameMapping::CopyFrom(const CollapsedNamesMap_ResourceNameMapping& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aapt.pb.CollapsedNamesMap.ResourceNameMapping)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CollapsedNamesMap_ResourceNameMapping::IsInitialized() const {
  return true;
}

void CollapsedNamesMap_ResourceNameMapping::InternalSwap(CollapsedNamesMap_ResourceNameMapping* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  swap(_impl_.id_, other->_impl_.id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CollapsedNamesMap_ResourceNameMapping::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ResourceMetadata_2eproto_getter, &descriptor_table_ResourceMetadata_2eproto_once,
      file_level_metadata_ResourceMetadata_2eproto[3]);
}

// ===================================================================

class CollapsedNamesMap::_Internal {
 public:
};

CollapsedNamesMap::CollapsedNamesMap(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:aapt.pb.CollapsedNamesMap)
}
CollapsedNamesMap::CollapsedNamesMap(const CollapsedNamesMap& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  CollapsedNamesMap* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_names_){from._impl_.resource_names_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:aapt.pb.CollapsedNamesMap)
}

inline void CollapsedNamesMap::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.resource_names_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

CollapsedNamesMap::~CollapsedNamesMap() {
  // @@protoc_insertion_point(destructor:aapt.pb.CollapsedNamesMap)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void CollapsedNamesMap::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.resource_names_.~RepeatedPtrField();
}

void CollapsedNamesMap::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void CollapsedNamesMap::Clear() {
// @@protoc_insertion_point(message_clear_start:aapt.pb.CollapsedNamesMap)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.resource_names_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CollapsedNamesMap::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .aapt.pb.CollapsedNamesMap.ResourceNameMapping resource_names = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_resource_names(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* CollapsedNamesMap::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:aapt.pb.CollapsedNamesMap)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .aapt.pb.CollapsedNamesMap.ResourceNameMapping resource_names = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_resource_names_size()); i < n; i++) {
    const auto& repfield = this->_internal_resource_names(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:aapt.pb.CollapsedNamesMap)
  return target;
}

size_t CollapsedNamesMap::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:aapt.pb.CollapsedNamesMap)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .aapt.pb.CollapsedNamesMap.ResourceNameMapping resource_names = 1;
  total_size += 1UL * this->_internal_resource_names_size();
  for (const auto& msg : this->_impl_.resource_names_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData CollapsedNamesMap::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    CollapsedNamesMap::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*CollapsedNamesMap::GetClassData() const { return &_class_data_; }


void CollapsedNamesMap::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<CollapsedNamesMap*>(&to_msg);
  auto& from = static_cast<const CollapsedNamesMap&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:aapt.pb.CollapsedNamesMap)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.resource_names_.MergeFrom(from._impl_.resource_names_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void CollapsedNamesMap::CopyFrom(const CollapsedNamesMap& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:aapt.pb.CollapsedNamesMap)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CollapsedNamesMap::IsInitialized() const {
  return true;
}

void CollapsedNamesMap::InternalSwap(CollapsedNamesMap* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.resource_names_.InternalSwap(&other->_impl_.resource_names_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CollapsedNamesMap::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ResourceMetadata_2eproto_getter, &descriptor_table_ResourceMetadata_2eproto_once,
      file_level_metadata_ResourceMetadata_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb
}  // namespace aapt
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::aapt::pb::ResourceMappings*
Arena::CreateMaybeMessage< ::aapt::pb::ResourceMappings >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aapt::pb::ResourceMappings >(arena);
}
template<> PROTOBUF_NOINLINE ::aapt::pb::ShortenedPathsMap_ResourcePathMapping*
Arena::CreateMaybeMessage< ::aapt::pb::ShortenedPathsMap_ResourcePathMapping >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aapt::pb::ShortenedPathsMap_ResourcePathMapping >(arena);
}
template<> PROTOBUF_NOINLINE ::aapt::pb::ShortenedPathsMap*
Arena::CreateMaybeMessage< ::aapt::pb::ShortenedPathsMap >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aapt::pb::ShortenedPathsMap >(arena);
}
template<> PROTOBUF_NOINLINE ::aapt::pb::CollapsedNamesMap_ResourceNameMapping*
Arena::CreateMaybeMessage< ::aapt::pb::CollapsedNamesMap_ResourceNameMapping >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aapt::pb::CollapsedNamesMap_ResourceNameMapping >(arena);
}
template<> PROTOBUF_NOINLINE ::aapt::pb::CollapsedNamesMap*
Arena::CreateMaybeMessage< ::aapt::pb::CollapsedNamesMap >(Arena* arena) {
  return Arena::CreateMessageInternal< ::aapt::pb::CollapsedNamesMap >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
